language: go
script: go test -race -cpu 1,2,4 -v -timeout 2m ./...
sudo: false
go:
  - 1.3
  - 1.4
  - tip
matrix:
  allow_failures:
    - go: tip
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/737918445727692fe8d1
    on_success: "change"  # options: [always|never|change] default: always
    on_failure: "always"  # options: [always|never|change] default: always
    on_start: false     # default: false
