language: go
script: ETCDTESTS=1 go test -race -cpu 1,2,4 -v -timeout 5m ./...
sudo: false
go:
  - 1.3.3
  - 1.4.3
  - 1.5.3
  - 1.6
  - tip
matrix:
  allow_failures:
    - go: tip
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/737918445727692fe8d1
    on_success: "change"  # options: [always|never|change] default: always
    on_failure: "always"  # options: [always|never|change] default: always
    on_start: false     # default: false
before_script:
  - curl -sL https://github.com/coreos/etcd/releases/download/v2.3.0/etcd-v2.3.0-linux-amd64.tar.gz | tar xz
  - etcd-v2.3.0-linux-amd64/etcd 2> /dev/null &
